# -*- coding: utf-8 -*-
# 翻译：曦颜XY 更新于：2020年07月27日 此文件和捐赠版文件移植,有捐赠版的可不必下载.
# 新浪微博 : https://weibo.com/xiyan1996
# B站：曦颜XY

# Main Menu
title_main = "主菜单"
title_choose = "选择项目:"
title_delete = "删除项目:"
title_extract = "解压选项:"
menu_create = "创建新项目"
menu_choose = "选择其它项目"
menu_delete = "删除项目"
menu_extract = "解压新ROM"
menu_updates = "检查更新"
menu_misc = "杂项工具"
menu_boot_recovery = "Boot/Recovery工具"
menu_rom_tools = "ROM工具菜单"
menu_new = "创建新项目"
menu_quit = "退出"
menu_back = "返回"
menu_skip = "跳过"

# ROM Tools Menu
menu_deodex = "Deodex化ROM"
menu_perm_type = "改变刷机脚本文件授权类型"
menu_root = "ROOT菜单"
menu_asserts = "机型验证菜单"
menu_extra_dir = "其它目录菜单"
menu_rom_debloat = "Debloat菜单"
menu_build_menu = "ROM打包菜单"

# Startup
startup_project = "当前项目："
startup_version = "安卓版本："
startup_mdepend = "缺少以下依赖: "
startup_need_java = "需正确安装并配置Java8或更高版本才能运行厨房。"
startup_copy_extract = "首先把你的ROM文件放到当前项目文件夹里"
startup_copy_extract2 = "然后你选择 选项4 就可以进行解包或其它操作 Ps.(汉化：曦颜XY)"
startup_title_no_rom = "当前项目文件夹里没有ROM文件"
startup_no_projects = "当前没有可用项目。"
startup_prep_updater_script = "准备updater-script中 ..."
startup_no_rom = "当前项目文件夹里没有ROM文件。"
startup_srkuser = "输入SuperR他服务器注册的账号用户名 (非XDA用户名和email地址)："
startup_srkuser_pass = "请输入账户密码: "
startup_srkuser_error = "不要输入email地址,是用户名。"
startup_srkuser_error2 = "账户用户名没在SuperR数据库里找到，或是"
startup_srkuser_error3 = "你的密码输错了，请再想想你的用户名和密码"
startup_srkuser_error4 = "试试:退出厨房再运行，再输入一遍。"
startup_srkuser_error5 = "就是这个网址输入的用户名:https://sr-code.com/down/。"
startup_srkuser_noauth = "此电脑未被授权,无法运行厨房(Ps.可以去XDA论坛私信SuperR解决)"
startup_srkuser_unknown = "发生未知错误. 请联系SuperR解决."
startup_srkuser_q = "确认是你的用户名?  y/n"
startup_srkpass_q = "是否在本地保存密码?  y/n"
startup_error = "初始化运行有点问题. 重新安装一下吧.(重新下载解压再运行)"
startup_checksum = "以下文件可能损坏了:"
startup_environ_error = "ε=(´ο｀*)))唉，当前系统环境下无法运行厨房"
startup_vdisk_error = "厨房无法在Live模式下的虚拟磁盘上运行"
startup_remdisk_error = "厨房无法在Live模式下在可移动磁盘上运行"

# Build
menu_build_zip = "创建新的ROM文件"
menu_sys_img = "创建img文件"
menu_sign = "签名当前项目文件夹里的所有刷机包文件"
donate_menu_zipalign = "Zipalign所有apk文件"
donate_menu_custom_id = "自定义ro.build.display.id"
menu_custom_zip = "自定义压缩菜单"
build_selinux_error = "你的安卓内核不支持selinux, 或者是厨房没在"
build_selinux_error2 = "boot里找到所需的文件，如果你能确定你的设备支持selinux"
build_selinux_error3 = "你可以复制boot.img中的ramdisk文件夹里file_contexts文件到"
build_selinux_error4 = "项目00_project_files目录里,然后你就可以继续了。"
build_selinux_error5 = "(#^.^#)"
build_selinux_error6 = "现在,你想要选择使用set_perm 或 raw_img。"
build_patient = "这要花费一点时间. 请耐心等待哈..."
build_prep_img = "正在准备img创建所需文件中 ..."
build_check_ziplog = "O(∩_∩)O哈哈~，出现错误. 请查看zip.log文件找找错误。"
build_prep_sys_img = "正在准备img创建所需文件中..."
build_img_error = "创建img文件过程中出现错误。"
build_img_which = "你要创建哪种img?"
build_img_nocon = "厨房没找到 file_contexts 这个文件. 确保你的"
build_img_nocon2 = "boot.img 是放在当前的ROM项目文件夹里, 或者"
build_img_nocon3 = "你复制boot.img解压的文件夹里file_contexts到"
build_img_nocon4 = "00_project_files这个文件夹里面,然后重试。"
build_no_zip = "当前目录没有可签名的刷机包。"
build_no_boot_q = "你的的刷机包里没有boot.img或kernel.img/ramdisk.img "
build_no_boot_q2 = "你确定不要内核相关文件仍然继续?  y/n"
build_cho_zip = "选择刷机包进行签名:"
build_man_img_size = "是否使用以下显示的大小数值?  y/n"
zipalign_q = "打包刷机包之前需要zipalign吗?  y/n  "
zipalign = "Zipalign "
zipalign_frame_q = "要对system/framework文件夹里所有apk执行zipalign吗?  y/n "
zipalign_complete = "Zipalign完成"
donate_bdisplay = "你想要你的刷机包在刷机时Recovery显示什么信息?"

# Custom zip
title_cho_cust_zip = "选择创建自定义zip文件："
cust_deldir_q = "您希望zip刷入前删除目录已存在的"
cust_deldir_q2 = "一些文件(夹)  y/n"
cust_meta_prep = "准备META-INF文件夹中..."
cust_not_exist = "老铁，你要压缩的文件夹不存在。"
cust_dir_info = "请确保你至少以下其中一项在"
cust_file_check = "请确保system,META-INF和boot.img在 "
cust_prep = "准备文件中 ..."
cust_convert_binary_q = "是否将updater-script转换为"
cust_convert_binary_q2 = "update-binary? y/n  "
cust_convert_binary = "转换中 ..."

# Debloat
menu_debloat = "Debloat ROM"
menu_debloat_cust = "自定义 Debloat"
menu_debloat_knox = "删除三星 Knox"
menu_debloat_restore = "还原 Bloat/Knox"
menu_debloat_refresh = "刷新 Bloat Status"
bloat_already_debloated = "当前ROM文件已经是debloated状态"
bloat_list_menu = "列出将被删除的文件"
bloat_list_files = "以下文件将被删除："
bloat_rem = "删除bloat中 ..."
bloat_moved = "Bloat已经被移动到:"
bloat_cust_info = "将一些东西添加到以下文件之一以使用此功能"
bloat_knox_not_exist = "ROM文件中没有Knox"
bloat_knox_rem = "删除knox中 ..."
bloat_knox_moved = "Knox已被移动到:"
bloat_no_files_restore = "没有需要还原的文件"
bloat_restore = "还原bloat中 ..."
bloat_has_restored = "已还原bloat。"
bloat_restore_q = "是否还原bloat?  y/n  "
debloated = "已Debloat"
bloated = "已Bloat"
bloat_dir_emply = "bloat_custom文件夹为空"

# Root
title_cho_root_zip = "选择需要添加Root的Zip:"
menu_root_method = "要哪种ROOT方式呢?"
menu_ss_method = "要安装哪种SuperSU呢?"
menu_supersucho = "还是让SuperSU决定"
menu_system_install = "安装System (SYSTEMLESS=false)"
menu_inject = "注入sepolicy的修改,并安装到system"
menu_download_inject = "下载/安装inject-sepolicy-addon"
menu_root_unroot = "Root/取消Root ROM"
menu_busybox = "添加/删除Busybox"
menu_add_remove_sud = "添加/删除 su.d 支持"
root_already = "已ROOT。"
root_must_add = "必须先添加ROOT."
busybox_already = "已有Busybox。"
busybox_q = "要添加Busybox吗?  y/n  "
root_sud_add_q = "要添加su.d吗?  y/n  "
root_sud_rem_q = "要移除su.d吗?  y/n  "
root_supersu_q = "SuperSU 已经不更新了. 你仍要添加吗?  y/n"
root_remove = "移除Root中 ..."

# General
general_remove_q = "要删除它吗?  y/n  "
general_continue_q = "是否继续?  y/n  "
general_cont_anyway_q = "灵魂拷问：仍然继续?  y/n  "
general_extracting = "提取"
general_create = "已创建在"
general_build = "正创建在"
no_python = "使用此功能需安装 Python3.5+ (曦颜提醒：如果还出问题，尝试切换默认系统Python版本后重试)。"
more_info_link = "若想了解其它信息，访问以下链接："
spaces_not_allowed = "不允许使用空格"

# Status
enabled = "已启用"
disabled = "已禁用"
add_support = "添加支持"
yes = "是"
no = "否"
secure = "Secure"
insecure = "Insecure"
no_knox = "没有Knox"
knox = "已存在Knox"
no_root = "未Root"

# Boot/Recovery Tools
title_boot = "Boot/Recovery工具菜单"
title_cho_boot = "选择boot.img或recovery.img"
title_unpack = "解包后会显示更多选项"
title_current = "当前: "
menu_pack_boot = "打包 "
menu_insecure = "Insecure/Secure 这个"
menu_dmverity = "删除 dm-verity"
menu_forcee = "添加/删除 forceencrypt"
menu_deopatch = "给安卓8.0 deodex化后patch sepolicy"
menu_deopatch_fail = "Patch失败, 可能sepolicy 已经patch了。"
menu_deopatch_sepol = "sepolicy不存在"
menu_deopatch_add = "安卓8.0 deodex后的sepolicy 已经patch了"
menu_unpack = "解包"
menu_boot_flashable = "创建刷机包："
menu_boot_restore = "恢复默认: "
menu_switch_boot = "在boot/recovery之间切换"
boot_repack = "打包 "
boot_repack_problem = "出现一个问题在打包你的"
boot_packed_d = " 已打包"
boot_no_img = "没有boot.img或recovery.img在"
boot_prop_warn = "请复制build.prop到项目目录并重试。"
boot_prep_build = "准备创建中 ..."
boot_unpack = "解包"
boot_unpack_problem = "出现一个问题在解包你的"
boot_unpack_noram = "在boot.img中没有ramdisk。"
boot_need_img = "你需要一个img文件来完成这个操作。"
boot_permission_error = "出现权限错误. 请检查boot.log文件"
boot_permission_error2 = "提供解决方法你看看："

# Plugin Manager
menu_plugin_menu = "插件管理"
menu_plugin_run = "运行插件"
menu_plugin_install = "安装插件"
menu_plugin_delete = "删除插件"
menu_plugin_updates = "检查插件更新"
menu_plugin_updates_info = "有可用更新："
menu_plugin_get = "获取插件列表中 ..."
menu_plugin_bashwin = "你不可以在windwos运行Bash插件。"
menu_plugin_bashwin2 = "使用插件管理去删除和重新安装正确的插件。"

# Misc Tools Menu
title_misc = "杂项工具菜单"
menu_language = "切换(重置)语言"
menu_heapsize = "Heapsize菜单"
menu_support = "支持: 创建zip发送"
menu_zip_devices = "压缩devices/capfiles文件夹并分享"
menu_ubinary = "update-binary选项"
menu_flashable = "刷机包zip文件选项(全局)"
menu_tools_reset = "重置所有工具"
menu_tools_reset_go = "移除所有工具中 ..."
menu_device_reset = "升级已知机型数据库(就是全世界ROM大佬用厨房处理过的手机型号)"
menu_choose_server = "主服务器位置"
menu_ext4exe = "使用make_ext4fs.exe"
menu_zip_compression = "ROM zip文件压缩等级"
menu_zip_compression2 = "输入所需的zip文件压缩等级"
menu_tools_update = "更新后必须退出厨房重新运行下"
menu_offline_auth = "离线授权菜单"
menu_offline_renew = "续订离线授权"
menu_offline_enable = "启用/禁用离线授权"
menu_renew_now = "现在续订"
auth_reset = "离线授权已启用/续订, 厨房需要重新启动。"
auth_reset2 = "首次重新启动需要电脑连接网络."
auth_max_days = "最长离线授权天数: "
auth_expired = "离线授权会话已到期。"
support_create = "创建support.zip ..."
support_finish = "Support zip已创建在项目目录里"
support_finish_up = "Support zip 已上传完毕"
heapsize_q = "请输入您的heapsize大小(单位MB)。"
heapsize_q2 = " 它必须小于你的总物理RAM："
heapsize_choose = "你想搞什么?"
heapsize_custom = "改变java的heapsize大小"
heapsize_reset = "恢复默认的heapsize大小检测"
heapsize_num_error = "必须输入一个数字(单位MB (例如: 1024))"
heapsize_error = "Heapsize必须小于等于物理RAM的大小."
heapsize_error2 = "(⊙o⊙)…"
physical_ram = "物理RAM： "
heapsize_auto = "默认"
ask_b = "每次在转换update-binary脚本文件时询问"
ask_s = "总是询问"
always_b = "总是转换到update-binary脚本"
always_s = "总是转换"
never_b = "从不转换到update-binary脚本"
never_s = "从不转换"
metasize = "短/长的(别乱想) set_metadata updater-script"
metasize_s = "短"
metasize_l = "长"
metasize_q = "你想设定多大的set_metadata updater-script ?"
brotli_q = "要使用 brotli 压缩吗？(dat.br)?"
brotli_level = "输入想要的 brotli 压缩等级"
brotli_menu = "sparse_dat brotli 压缩 (dat.br)"

# Asserts
menu_add_assert = "增加或删除机型"
menu_asserts_custom = "增加自定义机型验证"
menu_asserts_remove = "从ROM移除授权方式"
menu_asserts_reset = "恢复默认的机型验证"
asserts_no_assert = "没有机型验证要修改."
asserts_current = "当前机型验证: "
asserts_enter = "机型验证可以判断当前手机是否允许刷入ROM。"
asserts_enter2 = "如果你把一个ROM刷到一个错误的机型上,"
asserts_enter3 = "将会导致严重的问题! 我告诉你了哦，别怪我！"
asserts_enter4 = "请用英文逗号隔开机型授权方式。"
asserts_enter5 = "当前机型已经在列表中,请确保正确。"
asserts_enter6 = "按回车结束."
asserts_prep = "准备机型验证中 ..."
asserts_type = "在下面输入你的自定义验证，按回车键结束."
asserts_cust_error = "语法必须 "
asserts_prep_cust = "准备自定义机型验证中 ..."

# Extra Directory
menu_data = "/data/app"
menu_cust_dir = "自定义"
menu_cctr = "未启用"
extra_data_added = "/data/app 文件夹已添加. 请将第三方app放入:"
extra_already_data = "/data/app 文件夹已存在."
extra_already_data2 = "项目中的 /data 文件夹会保留."
extra_already_data3 = "要删除吗?  y/n"
extra_data_rem = "/data/app支持已删除"
extra_cust_name = "输入自定义目录的名称和刷入的位置，然后按ENTER键."
extra_cust_loc = "包含在你的ROM里的自定义目录在哪呢?"
extra_cust_name_q = "是否刷入到分区?  y/n"
extra_cust_setup = "配置"
extra_cust_add = "支持已添加"
extra_data = "Data授权类型:"
extra_data_q = "你要添加/data/app支持吗?  y/n  "
extra_data_perm = "请选择/data授权类型: "
extra_cust_already = " 已经存在。"

# Selection
select = "请选择:  "
select_enter = "请选择并回车:  "

# Notices
example = "例如:"
warning = "警告:"
notice = "注意:"
missing = "缺少文件:"
current = "当前"
expires = "到期:"
error = "错误:"
success = "成功:"
error_mess = "出现错误。"

# Press ENTER
enter_rom_tools = "按ENTER返回ROM工具菜单"
enter_continue = "按ENTER继续"
enter_main_menu = "按ENTER返回主菜单"
enter_boot_menu = "按ENTER返回到Boot/Recovery工具菜单"
enter_build_menu = "按ENTER返回刷机包创建菜单"
enter_change_perm_menu = "按ENTER返回改变授权方式菜单"
enter_debloat_menu = "按ENTER返回Debloat菜单"
enter_extra_dir_menu = "按ENTER返回到其它目录菜单"
enter_cho_another_detection = "按ENTER键选择另一种检测方法"
enter_ready = "准备好就按ENTER键"
enter_kitchen_updater = "按ENTER返回Kitchen更新"
enter_misc_tools_menu = "按ENTER返回杂项工具菜单"
enter_heapsize_menu = "按ENTER返回heapsize菜单"
enter_continue_extracting = "按ENTER继续提取"
enter_try_again = "按ENTER键重试"
enter_root_menu = "按ENTER返回ROOT菜单"
enter_plug_menu = "按ENTER返回到插件管理菜单"
enter_exit = "按ENTER键退出"

# Perm Type
perm_title = "更改/选择授权菜单"
perm_set_metadata_cur = "set_metadata"
perm_set_metadata = "set_metadata (对于版本在安卓4.4及以上)"
perm_set_perm = "set_perm (对于版本在安卓4.1及以下)"
perm_sparse = "Sparse dat"
perm_sparse_red = "Sparse dat (当前刷机包的设备不支持)"
perm_raw_img = "raw_img"
perm_check_symlinks = "检查软连接中 ..."
perm_set_metadata_error = "这个ROM不是 安卓4.4或更高"
perm_set_perm_error = "这个ROM不是安卓4.1或更低"
perm_changing_perm = "改变授权方式 ..."
perm_which = "你想使用哪种刷机脚本授权类型?"

# Delete Project
delete_has_been = " 已删除。"
delete_q = "要删除这个的项目?  y/n  "

# Deodex
deodex_copy_frame_prop = "您必须从ROM文件里将framework目录和"
deodex_copy_frame_prop2 = "build.prop文件复制到"
deodex_no_odex = "在这个ROM里没有odex文件。"
deodex_no_boot_oat = "在这个ROM里没有boot.oat文件，它不能deodex。"
deodex_no_plat = "该平台不支持该API的Deodex"
deodex_no_valgrind = "请安装valgrind后再次尝试"
deodex_disclaimer = "Deodex ROM后可能无法刷入。"
deodex_disclaimer2 = "你可能会收到错误,而且手机不一定能开机"
deodex_disclaimer3 = "（这是我(SuperR)知道的问题）,你最好确保自己知道如何解决."
deodex_disclaimer4 = "请不要因为这个问题找我(SuperR)问,谢谢 :)"
deodex_use_method = "使用哪种deodex方法?"
deodex_oat2dex_ver = "使用哪个oat2dex版本?"
deodex_oat2dex_official = "官方v0.86"
deodex_oat2dex_latest = "最新的版本"
title_cho_oat2dex = "选择oat2dex："
title_cho_smali = "选择smali："
title_cho_baksmali = "选择baksmali："
deodex_no_api = "无法获取当前Android版本."
deodex_config_arch = "设置下手机的arch。"
deodex_config_arch2 = "提示(arch具体为):"
deodex_config_arch3 = "检查framework文件夹, 里面可以看到另一个文件夹。"
deodex_config_arch4 = "文件夹的名字可能是以下之一："
deodex_config_arch5 = "(例如: arm, arm64, x86)。"
deodex_config_arch6 = "如果这里有问题, 检查以下问题："
deodex_config_arch7 = "1. 确保输入的arch参数是正确的。"
deodex_config_arch8 = "2. 确保ROM没有deodex化。"
deodex_config_arch9 = "输入手机的arch并且按回车继续。"
deodex_extract_txt = "提取odex文件中 ..."
deodex_extract = "...提取中"
deodex_move = "移动其它的app ..."
deodex_deop = "取消优化 boot.oat ..."
deodex_start_app = "开始 deodex化 /system/app ..."
deodex_start_priv = "开始 deodex化 /system/priv-app ..."
deodex_start_frame = "开始 deodex化 /system/framework ..."
deodex_deodexing = "...Deodex中"
deodex_app_already = " deodex已完成..."
deodex_clean = "清理中 ..."
deodex_complete = "Deodex化完成"
deodex_remain = "以下odex文件仍在您的ROM中"
deodex_method = "方法提示："
deodex_problems = "如果deodex化存在问题"
deodex_problems2 = "你刷入的ROM就可能有问题."
deodex_problems3 = "我告诉你了哦，个人建议:"
deodex_try_smali = "建议: 尝试用smali/baksmali"
deodex_api = "API等级: "
deodex_arch = "ARCH: "
deodex_arch2 = "ARCH2: "
deodex_move_odex = "移动odex文件 ..."
deodex_try_anyway = "仍要试试?  y/n  "
deodex_continue_q = "继续deodex化?  y/n  "
deodex_del_meta_inf_q = "Android 7.x版本使用APK签名方案v2,"
deodex_del_meta_inf_q2 = "这可能会导致deodex化时出现问题。"
deodex_del_meta_inf_q3 = "从所有apk文件中删除META-INF可能解决这个问题。"
deodex_del_meta_inf_q4 = "您是否要从ROM中的所有apk文件中"
deodex_del_meta_inf_q5 = "删除META-INF目录?  y/n  "
deodex_del_meta_inf = "从Apk文件里删除META-INF中..."
deodex_del_arch = "是否删除以下framework文件夹?  y/n"
deodex_pack_jar = "将dex打包进jar文件中..."
deodex_server_disabled = "目前不能使用云端服务器上的cdex转换"
deodex_server_cdex = "在云端服务器上转换cdex中 ..."
deodex_server_error1 = "上传失败"
deodex_server_error2 = "移动文件到工作目录失败"
deodex_server_error3 = "cdex zip文件提取失败"
deodex_server_error4 = "云端服务器上的dex zip文件创建失败"
deodex_no_dex = "在vdex中没有dex文件. 跳过中..."

# Extract
extract_title = "提取菜单"
extract_no_files_message = "1) 首先添加一个ROM zip文件、tar/boot.img、system.img或"
extract_no_files_message2 = "boot.img、win/boot.win,然后选择提取选项。"
extract_no_files_message3 = "2) 在已经ROOT的设备或在第三方Recovery中"
extract_no_files_message4 = "提取system、vendor、boot、和recovery的img文件。"
extract_cho_option = "选择提取方式"
extract_cho_option2 = "**如果遇到错误,请尝试另一种方式**"
extract_cho_option3 = "1) 手机启动在第三方Recovery (官方Recovery不可用)"
extract_cho_option4 = "2) 手机必须开机状态 (必须已经ROOT)"
extract_plug = "** 连接手机"
extract_detect_part = "正在检测分区信息 ..."
extract_detect_part2 = "如果遇到问题，请尝试更改USB模式"
extract_detect_part3 = "状态栏下拉连接模式改为媒体模式 (MTP)"
extract_pull_error = "出错了，可能是没有权限从设备里拉取img文件"
extract_pull_error2 = "(#^.^#)。"
extract_pulling = "拉取中 "
extract_prep = "正在准备提取中 ..."
extract_zip_fail = "这个zip文件厨房没办法提到任何东西"
extract_zip_fail2 = "o(╥﹏╥)o"
extract_zip = "提取zip中 ..."
extract_dat = "正在提取 system.new.dat、system.transfer.list和 boot.img中 ..."
extract_convert_br = "解压 dat.br ..."
extract_convert_sys = "转换到"
extract_img_from_zip = "正在从zip包中提取img文件 ..."
extract_tar_boot = "正在提取 system.ext4.tar.a 和 boot.img ..."
extract_img = "正在从img文件中提取 ..."
extract_fail = "提取过程中出现错误。"
extract_tar_md5 = "提取tar.md5文件中 ..."
extract_chunk = "提取 sparsechunks 和 boot.img ..."
extract_pbin = "提取 payload.bin ..."
extract_multi = "提取多 system ..."
extract_convert_chunk = "转换 sparse chunks 到 system.img ..."
extract_fix_img = "修复"
extract_general = "提取到"
extract_check_firm = "正在检测固件包 ..."
extract_tgz_fail = "该tgz文件似乎不是Nexus官方文件。"
extract_tgz_fail2 = ""
extract_files = "正在提取文件 ..."
extract_md5_fail = "在tar.md5文件中没有system.img.ext4"
extract_xz_fail = "此xz文件中没有system.img"
extract_tar_fail = "这个tar文件看起来不是android备份文件"
extract_tar = "提取名称"
extract_extra_extract_q = "您想提取其他的分区吗？(modem.bin, etc.)?  y/n  "
extract_cache_extract_q = "要提取cache.img?  y/n  "
extract_cache_include_q = "你想在ROM中包含cache.img中的文件吗？y/n"
extract_cache_include_q2 = ""
extract_cache = "添加cache.img文件中 ..."
extract_cache_fail = "在cache.img文件中没有csc.zip文件"
extract_rom_fail = "提取ROM中发生错误."
extract_rom_fail_ext4 = "您的img文件似乎不是有效的ext4文件(文件可能损坏)。"
extract_cho_part_detect = "选择分区大小检测方法"
extract_adb_shell = "通过adb shell"
extract_project_dir = "项目目录 (BETA): "
extract_manual = "手动输入"
extract_detect = "确定分区大小 "
extract_beta = "此功能是在BETA阶段，所以它可能无法正常刷入。"
extract_beta2 = "您可能会收到以下类似的错误:"
extract_beta3 = "blkdiscard failed: Invalid argument"
extract_beta4 = "您可以将授权方式更改为set_metadata或set_perm"
extract_beta5 = "来避免使用此功能"
extract_manual_bytes = "输入分区大小（单位：字节）"
extract_detect_fail = " 分区大小为空或不是数字，请重试。"
extract_sparse_convert = "检查并转换sparse img ..."
extract_img_fail = "没有"
extract_copy_e = "正在将文件复制到"
extract_moved_old_rom = "以下已被移动至:"
extract_q = "要提取 "
extract_q2 = "到当前项目目录吗?  y/n  "
extract_extra_extract = "要提取 "
extract_extra_q = "?  y/n  "
extract_extra_include = "你想包含哪些文件 "
extract_extra_include_q = " 在你的ROM中?  y/n  "
extract_autorom_sudo = "终端使用sudo模式运行厨房可以让AutoROM不意外中断"
extract_use_concat = "使用concatimg插件解压system.img"

# by-name
byname_how_to_get_q = "如何得到分区信息?"
menu_byname_detect_boot = "从boot.img/recovery.img里查询by-name代码 (强烈推荐)"
menu_byname_detect_device = "从设备检测by-name相关代码"
menu_byname_detect_manual = "手动输入by-name代码"
menu_byname_detect_mmc = "从recovery.img检测mmcblk分区信息"
byname_usb_debug = "** 在系统开发者选项里设置在Android设备上启用usb调试"
byname_usb_debug2 = "** 连接你的设备"
byname_usb_debug_root = "此操作需要root。"
byname_usb_debug_root2 = "可能需要手动在你的手机ROOT弹窗点击允许root。"
byname_error_device = "从设备中未检测到by-name相关代码。"
byname_error_device2 = "尝试从recovery.img中检测mmc分区信息"
byname_no_boot = "请复制boot.img, recovery.img, 或者kernel.elf到"
byname_no_boot2 = "项目目录，然后重试"
byname_which_img_q = "用哪个img文件?"
byname_detect = "检测by-name相关代码，从"
byname_no_files = "此项操作你需要boot.img, recovery.img, 或者kernel.elf."
byname_boot_fail = "未检测到by-name代码。"
byname_try_recovery = "尝试从recovery.img中检测mmc分区信息"
byname_detect_manual = "请输入您的by-name代码，然后按ENTER键"
byname_no_byname = "by-name代码对应的目录为空"
byname_create_mmc = "基于recovery.img创建mmc ..."
byname_need_recovery = "此项操作你需要recovery.img。"
byname_no_mmc = "厨房找不到mmc块信息。"
byname_recovery_fail = "在recovery.img中未检测到mmc相关代码。"
byname_try_boot = "尝试从boot.img文件中检测by-name代码"

# Signature
sig_info = "问题的意思就是"
sig_info2 = "创建的ROM刷入时TWRP会显示的信息以及"
sig_info3 = "ROM创建好后zip文件名。"
sig_info_q = "你的刷机包zip的名称是?"
sig_info_error = "ROM zip文件名里不要含有/符号"
donate_sig_cust = "要不要自定义显示ROM刷入时的一些信息？"
donate_sig_cust2 = "默认的信息写着Built with SuperR's Kitchen。"
donate_sig_q = "输入你的要显示的信息?"

# Zip devices
zipdev_info = "此选项将压缩您在厨房处理过的手机型号。"
zipdev_building = "创建device zip中 ..."
zipdev_uploading = "上传到服务器 ..."
zipdev_finished = "device zip已创建："
zipdev_upload = "你想要现在去上传, 然后就可以"
zipdev_upload2 = "添加到云端数据库供其他人使用?  y/n"
support_upload = "你要现在上传support zip 吗?  y/n"
xdauser_q = "你的XDA论坛用户名是(如果你没有就输入guest) ?"
zipdev_no_new = "device目录中没有你处理的新的手机型号。"

# Kitchen updater
update_check_kitchen = "检查更新 ..."
update_down = "厨房暂时停止所有文件操作。"
update_down2 = "请稍后再试。"
update_update_avail = "存在新版本!"
update_update_cv = "当期版本："
update_update_nv = "新版本："
update_update_now = "现在更新"
update_update_view = "查看更新日志"
update_changelog = "更新日志 (最新3个版本)："
update_updating = "更新中..."
update_finished = "SuperR's Kitchen 已更新，你需要重启厨房一下下"
update_already = "SuperR's Kitchen 已经是最新的"
update_check_launcher = "检查厨房启动器更新 ..."
update_launcher_avail = "启动器存在更新"
update_launcher_cv = "当前版本:"
update_launcher_nv = "新版本:"
update_launcher_finished = "安装程序/启动器已更新"
update_problem_download = "下载更新时出现问题。"
update_no_internet = "厨房无法正常联网。(推荐挂VPN)"
update_fail = "更新出错。"
update_fail2 = "试试重新下载最新的运行吧。"
update_fail3 = "非常抱歉带来不便。"
update_q = "现在更新吗?  y/n  "
update_auto_q = "你想在厨房启动时检查更新?  y/n  "
update_auto_toggle = "在启动时检查更新"
update_cred_fail = "您的付费用户信息认证未成功,因为在数据库中未找到你的信息。"
update_cred_fail2 = "你可以在你付费且注册完成后下载最新的厨房zip文件。"
update_cred_fail3 = "============"
update_reg_address = "下载地址:https://sr-code.com/reg.php"
update_verify = "检查所有文件校验码中 ..."
update_local = "是否安装本地更新安装包?  y/n"

# New Project
new_q = "请输入新项目名称(项目名例如: superr_这里是你终端输入的内容)："
new_already = "已有相同名称的项目"

# Plugin
donate_plugin_cho = "选择要运行的插件："
donate_plugin_install_cho = "选择要安装的插件："
donate_plugin_delete_cho = "选择要删除的插件："
donate_plugin_error = "插件脚本必须位于与插件脚本名称相同的目录中"
donate_plugin_error2 = ""
donate_plugin_server = "插件服务器未响应，请稍后再试"
donate_plugin_none = "没有要安装的新插件"
donate_plugin_reinstall_q = "无法检查更新，因为它是在系统更新之前安装的。"
donate_plugin_reinstall_q2 = "你想现在重新安装吗?  y/n"
donate_plugin_reinstall_q3 = ""
donate_plugin_crash = "插件中发生错误："
donate_plugin_crash2 = "请检查plugin.log文件。"
donate_plugin_incompat = "插件与当前电脑系统不兼容。"

# Sign
sign_ram_check = "检查运行内存中 ..."
sign_no_ram = "电脑没有足够的内存签名这个zip，试试电脑管家加速一下"
sign_signing = "签名"
sign_signed = "签名完成!"
sign_fail = "在签名中出现错误。"
sign_q = "要签名zip文件吗?  y/n "

# Build img
img_add = "添加"
img_flash_fail = "无法刷入，因为缺少分区信息"
img_flash_fail2 = ""
img_create_dat = "创建sparse dat镜像"
img_create_symlinks = "创建 symlinks"
img_create_raw = "创建"
img_fail = "创建img文件中出现错误。"
img_fail_size = "无法确定分区大小。"
img_fail_fit = "创建失败, 目录不匹配："
img_fail_log = "创建失败. 检查img_build.log文件。"
img_dir_open = "确保你的system文件夹没有被系统文件管理器打开后重试。"
img_dir_open2 = "就是可能存在资源占用，你懂得。"
img_flash_failB = "无法刷入, 因为缺少分区信息"
img_flash_failB2 = "请创建一个device文件夹"
img_flash_failB3 = "或着在ROM zip创建后手动插入分区信息"
img_sparse_q = "想创建什么类型的img?"

# Language
reset_language = "语言设定已重置，请重启下厨房"
lang_added = "英文语言文件已更新，请查看Diff。"
lang_translate = "请校对一下中文文件。"

# Tools
tools_dl = "下载"
tools_dl_failed = "所需工具下载失败,最好挂VPN后下载："
tools_dl_install_failed = "所需工具下载/安装失败。"
tools_dl_device_failed = "无法下载一些机型数据库。"
tools_dl_device_failed2 = "稍后使用杂项工具菜单 --> 升级机型数据库到最新的版本"
tools_dl_device_failed3 = ""
wintools_dl = "(大概要下载 17MB 大小文件)"
lintools_dl = "(大概要下载 24MB 大小文件)"
tools_need = "要安装厨房相关工具后才能正常使用。"
tools_dl_install = "下载/安装中..."
tools_dl_q = "是否现在下载/安装?  y/n  "

#Example Plugin
plug_example_text = "添加更多插件到"
